name: profiles
description: AI Profile management for Metalore.
version: 0.5.1
publish_to: 'none'

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  mcp:
    path: ../mcp
  hive_flutter: ^1.1.0
  uuid: ^4.5.2
  json_annotation: ^4.9.0
  meta: ^1.17.0

dev_dependencies:
  build_runner: ^2.4.13
  json_serializable: ^6.8.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
